### ISSUE TITLE
No video displays when clicking play (audio is heard) in SampleVideoPlayer, unable to use to verify functionality for DAI DASH stream

### ISSUE THREAD

**Issue by mikesalvia** [googleads/googleads-ima-android-dai#16]
![Screenshot_1594137873](https://user-images.githubusercontent.com/6209204/86809612-0ad3ff80-c04a-11ea-8cd9-ce9158031665.png)

Additionally, the DAI Test Samples page for HTML5 SDK is down and does not seem to be working, not sure if this is related, but just another informational bit.

**Comment by mikesalvia** [comment]
Any update on why this maybe happening?

**Comment by Kiro705** [comment]
Hello @mikesalvia ,

Is the issue still reproducible for you using the [latest sample apps](https://github.com/googleads/googleads-ima-android-dai/releases/tag/3.25.1-0)? I tested it, and was able to see the sample stream play.

Please feel free to reopen the issue if it is still happening for you, with steps on how to reproduce.
