### ISSUE TITLE
Closed Caption not working

### ISSUE THREAD

**Issue by m9jpatidar** [googleads/googleads-ima-android-dai#2]
closed caption is not working for in this sample in both SampleVideoPlayer, BasicExample and AdvanceExample, where as same assets key showing closed caption for tvOS and Roku platforms.

**Comment by achampagne-ensemble** [comment]
I am having the same issue on the latest release (3.26.0)

**Comment by Kiro705** [comment]
Hello @achampagne-ensemble ,

Do you have any steps to reproduce this issue?
Including stream, sample, actions in app, and any code changes.

**Comment by achampagne-ensemble** [comment]
It appears the issue is with the captions that are returned from the doubleclick endpoint .m3u8 response.  The .vtt file contains the wrong captions, and I believe this is causing the issue.
