### ISSUE TITLE
VideoStreamPlayer leaked when closing the app.

### ISSUE THREAD

**Issue by tiborviktorpasztor** [googleads/googleads-ima-android-dai#30]
Library version:
    implementation 'com.google.ads.interactivemedia.v3:interactivemedia:3.24.0'
    implementation 'com.google.android.exoplayer:exoplayer:2.13.3'
    
Device tested on:
   Pixel 4 emulator running API 29
   
Steps to reproduce:
- Clone repo, open BasicExample. 
- Add a simple log into SampleAdsWrapper.createVideoStreamPlayer()'s getContentProgress() method, line 290.
```
      @Override
      public VideoProgressUpdate getContentProgress() {
        Log.d("SampleAdsWrapper", "getContentProgress()"+this);
        return new VideoProgressUpdate(
            videoPlayer.getCurrentPositionMs(), videoPlayer.getDuration());
      }
```
- Start the app, start playback.
- Close the app with the back button. Observe logs. Polling for getContentProgress() does not stop.
- Open the app again, start playback. Observe logs. Notice that there are now two different instances polling for progress.
- This can be repeated multiple times, and the logs will keep on multiplying with 3, 4.. etc instances polling. The only way to stop this, is to kill the app in the task manager.

I couldn't find any public api to handle this, but if there is one already, it should be part of the sample apps too.

Thank you!

**Comment by Kiro705** [comment]
Hello @tiborviktorpasztor ,

Thank you for raising this issue. Unfortunately, based on the limited focus of the BasicExample, it does not properly dispose of the player to stope this polling when the app is closed.

I would recommend looking at how the AdvancedExample handles back button clicks, as polling does not continue in that app. This should be more similar for how production apps will handle these interactions than what is seen in the BasicExample.

Thank you,
Jackson
IMA SDK team
