### ISSUE TITLE
Ad events are missing when app resumes from background 

### ISSUE THREAD

**Issue by AndreyPogorely** [googleads/googleads-ima-android-dai#66]
Hello,

We are seeing missing ad events when app is put into background and is put into foreground after ~60 seconds. The video controls are also affected. We can reproduce the issue in our apps (Paramount).

Steps to reproduce:
1. Install and load [Advanced Example from the latest Google Ads IMA SDK Android Examples for DAI](https://github.com/googleads/googleads-ima-android-dai/releases)
2. Play a VOD video
3. Background the app during an ad in THIRD_QUARTILE
4. Wait for over ~60 seconds
5. Foreground the app

Expected:
1. Ad continues to play and publish ad events
```
CUEPOINTS_CHANGED
AD_BREAK_STARTED
CUEPOINTS_CHANGED
LOADED
STARTED
FIRST_QUARTILE
MIDPOINT
THIRD_QUARTILE
COMPLETED
AD_BREAK_ENDED
```

Observed:
1. Ad continues to play without publishing new ad events (COMPLETED, AD_BREAK_ENDED), content resumes playing. Video controls are missing and app doesn’t respond to click events.

Tested on `3.89.2` and `3.29.0` (`3.30.0` crashes in the sample app when any video is played `java.lang.IllegalStateException: Android TV ads library should be called from an Android TV app`). 

Device: Samsung-SM-G935A (API 26)

**Comment by Kiro705** [comment]
Hello @AndreyPogorely ,

This same issue was raised by your team to the IMA SDK issues queue. I am going to close this issue and recommend following up on the email thread.

Thank you,
Jackson
IMA SDK team
